---
name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.12.0
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm
      - name: Install packages
        run: pnpm install
      - name: Run tests
        run: pnpm test
